import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Xone | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Xone!
        </h1>

        <p className={styles.description}>
          Get started by Joining us
        </p>

        <div className={styles.grid}>
          <a href="https://xone-world.slack.com" className={styles.card}>
            <h2>Join Us &rarr;</h2>
            <p>Join our community on slack channel to learn and grow with us</p>
          </a>

          <a href="/blog" className={styles.card}>
            <h2>Blog &rarr;</h2>
            <p>Read our awesome list of curated content for the devs and by the devs</p>
          </a>

        </div>
      </main>
    </div>
  )
}
